# -*- coding: utf-8 -*-
"""wykresy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zE1q4el_lxGgkYMCxB8UT1jtdaO6jnl1
"""

import matplotlib.pyplot as plt

# Rozmiary danych
sizes = [10000, 20000, 50000, 70000, 100000]

# Nazwy operacji
operations = [
    "Dodawanie na początek",
    "Dodawanie na koniec",
    "Dodawanie na indeks",
    "Usuwanie z początku",
    "Usuwanie z końca",
    "Usuwanie z indeksu",
    "Wyszukiwanie 77"
]

# Czas operacji dla tablicy [ms]
array_times = [
    [176.634, 0.799, 385.710, 640.114, 0.053, 89.335, 0.252],
    [740.658, 0.323, 1061.170, 2214.727, 0.112, 295.086, 0.499],
    [3922.944, 0.860, 6755.013, 14398.318, 0.327, 1893.011, 0.168],
    [6614.584, 0.808, 13129.140, 28235.608, 0.323, 4448.018, 0.922],
    [13127.517, 1.269, 27040.134, 62889.628, 0.934, 7789.101, 0.172]
]

# Czas operacji dla listy [ms]
list_times = [
    [3.452, 2949.277, 316.375, 1.891, 1087.200, 200.391, 0.550],
    [7.112, 6640.412, 912.396, 3.308, 4430.258, 888.098, 1.045],
    [7.868, 58712.404, 7382.713, 10.075, 49603.477, 7304.745, 1.004],
    [10.349, 146865.047, 14586.163, 11.959, 160014.598, 17875.273, 1.960],
    [19.184, 369906.674, 39824.946, 27.658, 352389.753, 45093.036, 2.346]
]

# Generowanie wykresów
for i, operation in enumerate(operations):
    array_op_times = [array_times[j][i] for j in range(len(sizes))]
    list_op_times = [list_times[j][i] for j in range(len(sizes))]

    plt.figure(figsize=(8, 5))
    plt.plot(sizes, array_op_times, label="Tablica", marker='o')
    plt.plot(sizes, list_op_times, label="Lista", marker='s')
    plt.title(f'Czas operacji: {operation}')
    plt.xlabel('Liczba elementów')
    plt.ylabel('Czas [ms]')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

# Wyświetl wszystkie wykresy na raz
plt.show()